project_id = "lyqozlofyngahpslmwti"

[functions.sync-gameweek-history]
verify_jwt = false

[functions.sync-price-changes]
verify_jwt = false

[functions.sync-upcoming-fixtures]
verify_jwt = false

[functions.predict-price-changes]
verify_jwt = false

[functions.predict-form-trends]
verify_jwt = false